### PR TITLE
Updates badger support to v2

### PR DESCRIPTION
**Pull request by nullstyle**
Note:  I was wanting to add pebble support to hidalgo (see: https://github.com/hidal-go/hidalgo/compare/master...nullstyle:pebble?expand=1) and it turns out it was easier to just update badger first

### CODE REVIEW

**Comment by dennwc** [comment]
The change looks good overall, but I see a lot of unrelated changes to `go.mod` and `go.sum`. Can you please rollback those two files and run `go mod tidy`? We can update all other dependencies in a separate PR, if required.

**Comment by nullstyle** [comment]
@dennwc Those changes to go.mod and go.sum actually are the results from running `go mod tidy`.  This change itself was motivated because the badger guys included breaking changes when going from 1.5.4 to 1.6, which was being automatically applied when running `go mod tidy`

**Comment by dennwc** [comment]
Merged manually. Sorry for a huge delay :man_facepalming:

**Comment by nullstyle** [comment]
@dennwc No worries my dude! Have a good day

**Pull request closed without merging**
